---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.6
    run_list:
      - recipe[apt]
      - recipe[couchdb]
  - name: debian-8.2
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[couchdb::source]
    attributes:
      couch_db:
        src_version: 1.6.1
        src_checksum: 5a601b173733ce3ed31b654805c793aa907131cd70b06d03825f169aa48c8627

suites:
  - name: faraday
    run_list:
      - recipe[faraday]
      - recipe[faraday::config]
      - recipe[faraday-lwrp::config]
    attributes:
      faraday:
        install_dir: /opt/faraday-test
        user: kitchen
  - name: faraday-server
    run_list:
      - recipe[faraday]
      - recipe[faraday::service]
    attributes:
      faraday:
        install_dir: /opt/faraday-test
        service:
          RUN: true
  - name: faraday-cscan
    run_list:
      - recipe[faraday]
      - recipe[faraday::cscan]
      - recipe[faraday-lwrp::cscan]
    attributes:
      faraday:
        install_dir: /opt/faraday-test
        cscan:
          ips:
            - 127.0.1.1
          websites:
            - https://localhost:443
