---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: debian-7
    run_list:
      - recipe[apt]
      - recipe[couchdb]
  - name: debian-8
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[couchdb::source]
    attributes:
      couch_db:
        src_version: 1.6.1
        src_checksum: 5a601b173733ce3ed31b654805c793aa907131cd70b06d03825f169aa48c8627

suites:
  - name: faraday
    run_list:
      - recipe[faraday]
      - recipe[faraday::config]
      - recipe[faraday::cscan]
    attributes:
      faraday:
        install_dir: /opt/faraday-test
        user: root
  - name: faraday-server
    run_list:
      - recipe[faraday]
      - recipe[faraday::service]
    attributes:
      faraday:
        install_dir: /opt/faraday-test
        service:
          DAEMON_ARGS: --gui=no-gui
