---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  chef_license: accept

platforms:
  - name: debian-8.2
    run_list:
      - recipe[apt]
      - recipe[build-essential]
    attributes:
      couch_db:
        configure_flags: ""

suites:
  - name: faraday
    run_list:
      - recipe[faraday::couchdb]
      - recipe[faraday::sources]
      - recipe[faraday::config]
      - recipe[faraday-lwrp::config]
    attributes:
      faraday:
        install_dir: /opt/faraday-test
        user: kitchen
  - name: faraday-server
    run_list:
      - recipe[faraday::couchdb]
      - recipe[faraday::sources]
      - recipe[faraday::service]
      - recipe[faraday::server]
    attributes:
      faraday:
        user: faraday
        install_dir: /opt/faraday-test
        service:
          RUN: true
          INSTALL_DIR: /opt/faraday-test
          DAEMON: faraday-server.py
          DAEMON_ARGS: --debug
  - name: faraday-cscan
    run_list:
      - recipe[faraday::couchdb]
      - recipe[faraday::sources]
      - recipe[faraday::cscan]
      - recipe[faraday-lwrp::cscan]
    attributes:
      faraday:
        install_dir: /opt/faraday-test
        cscan:
          ips:
            - 127.0.1.1
          websites:
            - https://localhost:443
