---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-7.6

suites:
- name: faraday
  run_list:
  - recipe[apt]
  - recipe[couchdb]
  - recipe[faraday]
  - recipe[faraday::config]
  attributes:
    couchdb:
      httpd:
        bind_address: 127.0.0.1
        database_dir: /var/lib/couchdb
    faraday:
      install_dir: /opt/faraday-test
      user: vagrant
