# -*- coding: utf-8 -*-

require 'chefspec'
require 'chefspec/berkshelf'

describe 'faraday::config' do
  let(:subject) do
    ChefSpec::SoloRunner.new do |node|
      node.set['faraday']['user'] = 'faraday'
      node.set['faraday']['group'] = 'faraday'
      node.set['faraday']['home'] = '/home/faraday'
      node.set['faraday']['config']['appname'] = 'Faraday - PTI'
      node.set['faraday']['config']['version'] = '13.37'
      node.set['faraday']['config_attrs']['appname'] = { foo: 'bar' }
    end.converge described_recipe
  end

  it 'creates directory[/home/faraday/.faraday/config]' do
    expect(subject).to create_directory('/home/faraday/.faraday/config')
      .with(owner: 'faraday',
            group: 'faraday',
            recursive: true)
  end

  it 'creates template[/home/faraday/.faraday/config/config.xml]' do
    config_file = '/home/faraday/.faraday/config/config.xml'
    matches = [/<!-- Generated by Chef! Do not edit/,
               %r{<appname foo="bar">Faraday - PTI</appname>},
               %r{<version>13.37</version>}]

    expect(subject).to create_template(config_file)
      .with(owner: 'faraday',
            group: 'faraday',
            source: 'config.xml.erb')

    matches.each do |m|
      expect(subject).to render_file(config_file).with_content(m)
    end
  end
end
